apiVersion: v1
kind: Service
metadata:
  name: front-app
  namespace: python-demo-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 5000
  selector:
    app: front-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-service
  name: front-app
  namespace: python-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - command:
        - venv/bin/python
        - -m
        - flask
        - --app
        - front_app
        - run
        - -h
        - 0.0.0.0
        - -p
        - "5000"
        env:
        - name: APP_BACK_APP_HOST
          value: back-app.mlakewood.svc.cluster.local
        - name: APP_BACK_APP_PORT
          value: "8081"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: grpc://simplest-collector.opentelemetry.svc.cluster.local:4317
        - name: ENV
          value: prod
        image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/front-app
        name: front-app
        ports:
        - containerPort: 5000
