apiVersion: v1
kind: Service
metadata:
  name: front-app
  namespace: python-demo-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 5000
  selector:
    app: front-app
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-tests
  namespace: python-demo-app
spec:
  metrics:
  - name: integration-tests
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/argocd-test-integration-tests:main-9183cc6
                name: integration-tests
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: front-app
  namespace: python-demo-app
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: front-app
  strategy:
    canary:
      canaryMetadata:
        labels:
          release: canary
      canaryService: front-app-canary
      stableMetadata:
        labels:
          release: stable
      stableService: front-app
      steps:
      - setCanaryScale:
          matchTrafficWeight: true
          replicas: 1
      - analysis:
          templates:
          - templateName: integration-tests
      - setWeight: 20
      - pause:
          duration: 1m
      - setWeight: 40
      - pause:
          duration: 1m
      - setWeight: 60
      - pause:
          duration: 1m
      - setWeight: 80
      - pause:
          duration: 1m
      trafficRouting:
        managedRoutes:
        - name: production
        - name: canary
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - env:
        - name: APP_BACK_APP_HOST
          value: back-app.mlakewood.svc.cluster.local
        - name: APP_BACK_APP_PORT
          value: "8081"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: grpc://simplest-collector.opentelemetry.svc.cluster.local:4317
        name: front-app
