apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: python-demo-app
  name: python-demo-app
---
apiVersion: v1
kind: Service
metadata:
  name: back-app
  release: stable
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 5000
  selector:
    app: back-app
---
apiVersion: v1
kind: Service
metadata:
  name: back-app-canary
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 5000
  selector:
    app: back-app
    release: canary
---
apiVersion: v1
kind: Service
metadata:
  name: front-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 5000
  selector:
    app: front-app
    release: stable
---
apiVersion: v1
kind: Service
metadata:
  name: front-app-canary
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 5000
  selector:
    app: front-app
    release: canary
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-tests
spec:
  metrics:
  - name: integration-tests
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/argocd-test-integration-tests:main-efa0329
                name: integration-tests
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: back-app
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: back-app
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 1m
      - analysis:
          templates:
          - templateName: integration-tests
      - setWeight: 40
      - pause:
          duration: 1m
      - setWeight: 60
      - pause:
          duration: 1m
      - setWeight: 80
      - pause:
          duration: 1m
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/back-app:main-efa0329
        name: back-app
        ports:
        - containerPort: 5000
          name: webserver
        readinessProbe:
          httpGet:
            path: /message
            port: webserver
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: front-app
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: front-app
  strategy:
    canary:
      canaryMetadata:
        labels:
          release: canary
      canaryService: front-app-canary
      stableMetadata:
        labels:
          release: stable
      stableService: front-app
      steps:
      - setCanaryScale:
          matchTrafficWeight: true
          replicas: 1
      - analysis:
          templates:
          - templateName: integration-tests
      - setWeight: 20
      - pause:
          duration: 1m
      - setWeight: 40
      - pause:
          duration: 1m
      - setWeight: 60
      - pause:
          duration: 1m
      - setWeight: 80
      - pause:
          duration: 1m
      trafficRouting:
        managedRoutes:
        - name: production
        - name: canary
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/front-app:main-efa0329
        name: front-app
        ports:
        - containerPort: 5000
          name: webserver
        readinessProbe:
          httpGet:
            path: /
            port: webserver
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
