apiVersion: v1
kind: Namespace
metadata:
  name: python-demo-app
---
apiVersion: v1
kind: Service
metadata:
  name: python-demo-app-web
  namespace: python-demo-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: gunicorn
  selector:
    app: python-demo-app
    role: web
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-tests
  namespace: python-demo-app
spec:
  metrics:
  - name: integration-tests
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/argocd-test-integration-tests:main-9880487
                name: integration-tests
              restartPolicy: Never
