apiVersion: v1
kind: Namespace
metadata:
  name: python-demo-app
---
apiVersion: v1
kind: Service
metadata:
  name: python-demo-app-web
  namespace: python-demo-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: gunicorn
  selector:
    app: python-demo-app
    role: web
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-tests
  namespace: python-demo-app
spec:
  metrics:
  - name: integration-tests
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/argocd-test-integration-tests:main-32d0ac6
                name: integration-tests
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: python-demo-app
  namespace: python-demo-app
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: python-demo-app
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - analysis:
          templates:
          - templateName: integration-tests
      - setWeight: 40
      - pause:
          duration: 1m
      - setWeight: 60
      - pause:
          duration: 1m
      - setWeight: 80
      - pause:
          duration: 1m
  template:
    metadata:
      labels:
        app: python-demo-app
    spec:
      containers:
      - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/argocd-test:main-cabe67a
        name: python-demo-app
        ports:
        - containerPort: 5000
          name: webserver
        readinessProbe:
          httpGet:
            path: /
            port: webserver
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
