apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo-app-web
  namespace: python-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demo-app
      role: web
  template:
    metadata:
      labels:
        app: python-demo-app
        role: web
    spec:
      containers:
      - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/argocd-test:main-ea1f1eb
        name: python-demo-app
        ports:
        - containerPort: 5000
          name: webserver
        readinessProbe:
          httpGet:
            path: /
            port: webserver
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
