apiVersion: v1
kind: Service
metadata:
  name: back-app
  namespace: python-demo-app
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 5000
  selector:
    app: back-app
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-tests-back-app
  namespace: python-demo-app
spec:
  metrics:
  - name: integration-tests-back-app
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/argocd-test-integration-tests:main-8b6e9f5
                name: integration-tests
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: web-service
  name: back-app
  namespace: python-demo-app
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: back-app
  strategy:
    canary:
      canaryMetadata:
        labels:
          release: canary
      canaryService: back-app-canary
      stableMetadata:
        labels:
          release: stable
      stableService: back-app
      steps:
      - setCanaryScale:
          matchTrafficWeight: true
          replicas: 1
      - analysis:
          templates:
          - templateName: integration-tests
      - setWeight: 40
      - pause:
          duration: 1m
      - setWeight: 60
      - pause:
          duration: 1m
      - setWeight: 80
      - pause:
          duration: 1m
      trafficRouting:
        managedRoutes:
        - name: production
        - name: canary
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - command:
        - venv/bin/python
        - -m
        - flask
        - --app
        - back_app
        - run
        - -h
        - 0.0.0.0
        - -p
        - "5000"
        env:
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: grpc://simplest-collector.opentelemetry.svc.cluster.local:4317
        image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/back-app:main-8b6e9f5
        name: back-app
        ports:
        - containerPort: 5000
          name: webserver
        readinessProbe:
          httpGet:
            path: /message
            port: webserver
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
